# coding: utf-8

"""
    DRF Endpoint Examples

    Swagger API Documentation for DRF Endpoint Examples.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.api_api import ApiApi  # noqa: E501
from swagger_client.rest import ApiException


class TestApiApi(unittest.TestCase):
    """ApiApi unit test stubs"""

    def setUp(self):
        self.api = ApiApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_address(self):
        """Test case for create_address

        """
        pass

    def test_create_customer(self):
        """Test case for create_customer

        """
        pass

    def test_create_order(self):
        """Test case for create_order

        """
        pass

    def test_create_product(self):
        """Test case for create_product

        """
        pass

    def test_create_review(self):
        """Test case for create_review

        """
        pass

    def test_destroy_address(self):
        """Test case for destroy_address

        """
        pass

    def test_destroy_customer(self):
        """Test case for destroy_customer

        """
        pass

    def test_destroy_order(self):
        """Test case for destroy_order

        """
        pass

    def test_destroy_product(self):
        """Test case for destroy_product

        """
        pass

    def test_destroy_review(self):
        """Test case for destroy_review

        """
        pass

    def test_list_address(self):
        """Test case for list_address

        """
        pass

    def test_list_customers(self):
        """Test case for list_customers

        """
        pass

    def test_list_orders(self):
        """Test case for list_orders

        """
        pass

    def test_list_products(self):
        """Test case for list_products

        """
        pass

    def test_list_reviews(self):
        """Test case for list_reviews

        """
        pass

    def test_partial_update_address(self):
        """Test case for partial_update_address

        """
        pass

    def test_partial_update_customer(self):
        """Test case for partial_update_customer

        """
        pass

    def test_partial_update_order(self):
        """Test case for partial_update_order

        """
        pass

    def test_partial_update_product(self):
        """Test case for partial_update_product

        """
        pass

    def test_partial_update_review(self):
        """Test case for partial_update_review

        """
        pass

    def test_retrieve_address(self):
        """Test case for retrieve_address

        """
        pass

    def test_retrieve_customer(self):
        """Test case for retrieve_customer

        """
        pass

    def test_retrieve_order(self):
        """Test case for retrieve_order

        """
        pass

    def test_retrieve_product(self):
        """Test case for retrieve_product

        """
        pass

    def test_retrieve_review(self):
        """Test case for retrieve_review

        """
        pass

    def test_update_address(self):
        """Test case for update_address

        """
        pass

    def test_update_customer(self):
        """Test case for update_customer

        """
        pass

    def test_update_order(self):
        """Test case for update_order

        """
        pass

    def test_update_product(self):
        """Test case for update_product

        """
        pass

    def test_update_review(self):
        """Test case for update_review

        """
        pass


if __name__ == '__main__':
    unittest.main()
