# coding: utf-8

# flake8: noqa
"""
    DRF Endpoint Examples

    Swagger API Documentation for DRF Endpoint Examples.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.address import Address
from swagger_client.models.customer import Customer
from swagger_client.models.order import Order
from swagger_client.models.product import Product
from swagger_client.models.review import Review
